name = "video-dl"
main = "src/index.ts"
compatibility_date = "2026-07-01"
workers_dev = false

routes = [
  { pattern = "video-dl.cajuos.dev", custom_domain = true }
]

[vars]
ALLOWED_ORIGIN = "https://cajuos.dev"

[triggers]
crons = []
