name = "video-dl"
main = "src/index.ts"
compatibility_date = "2026-07-01"
workers_dev = false

routes = [
  { pattern = "video-dl.cajuos.dev", custom_domain = true }
]

[vars]
ALLOWED_ORIGIN = "https://cajuos.dev"

[[kv_namespaces]]
binding = "VIDEO_DL_CACHE"
id = "96f97fdb3a984003836924ce5ca238b8"

[triggers]
crons = []
